const SIGN_UP_REDUCER_ACTIONS = {
	update_firstname:           	 			"UPDATE_FIRSTNAME",
	update_lastname:           	 	 			"UPDATE_LASTNAME",
	update_email:               	 			"UPDATE_EMAIL",
	update_password:            	 			"UPDATE_PASSWORD",
	update_account_type: 			 			"UPDATE_ACCOUNT_TYPE",
	update_contact_number:      	 			"UPDATE_CONTACT_NUMBER",
	update_language: 				 			"UPDATE_LANGUAGE",
	update_country: 				 			"UPDATE_COUNTRY",
	update_city: 					 			"UPDATE_CITY",
	update_business_type: 			 			"UPDATE_BUSINESS_TYPE",
	update_business_name: 			 			"UPDATE_BUSINESS_NAME",
	update_business_address: 		 			"UPDATE_BUSINESS_ADDRESS",
	update_got_shop_already_with_us: 			"UPDATE_GOT_SHOP_ALREADY_WITH_US",
	update_validated: 							"UPDATE_VALIDATED",
	update_firstname_error:           	 		"UPDATE_FIRSTNAME_ERROR",
	update_lastname_error:           	 	 	"UPDATE_LASTNAME_ERROR",
	update_email_error:               	 		"UPDATE_EMAIL_ERROR",
	update_password_error:            	 		"UPDATE_PASSWORD_ERROR",
	update_account_type_error: 			 		"UPDATE_ACCOUNT_TYPE_ERROR",
	update_contact_number_error:      	 		"UPDATE_CONTACT_NUMBER_ERROR",
	update_language_error: 				 		"UPDATE_LANGUAGE_ERROR",
	update_country_error: 				 		"UPDATE_COUNTRY_ERROR",
	update_city_error: 					 		"UPDATE_CITY_ERROR",
	update_business_type_error: 			 	"UPDATE_BUSINESS_TYPE_ERROR",
	update_business_name_error: 			 	"UPDATE_BUSINESS_NAME_ERROR",
	update_business_address_error: 		 		"UPDATE_BUSINESS_ADDRESS_ERROR",
	update_got_shop_already_with_us_error: 		"UPDATE_GOT_SHOP_ALREADY_WITH_US_ERROR",
};

export default SIGN_UP_REDUCER_ACTIONS;